# Generated by Django 4.2.16 on 2024-11-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friendList',
            field=models.ManyToManyField(blank=True, related_name='users', to='users.friends'),
        ),
    ]
