# Generated by Django 4.2.16 on 2024-11-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_friendlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friends',
            name='sharesCalendar',
        ),
        migrations.AddField(
            model_name='friends',
            name='requestPending',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='friends',
            name='viewable',
            field=models.BooleanField(default=True),
        ),
    ]
