# Generated by Django 4.2.16 on 2024-11-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_event_end_time_alter_event_start_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
