# Generated by Django 4.2.16 on 2024-11-16 06:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_alter_event_end_time_alter_event_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 7, 18, 53, 256894, tzinfo=datetime.timezone.utc)),
        ),
    ]
