# Generated by Django 4.2.16 on 2024-11-21 23:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_event_end_time_event_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 0, 38, 29, 209482, tzinfo=datetime.timezone.utc)),
        ),
    ]
