# Generated by Django 4.2.16 on 2024-11-21 23:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0006_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 22, 0, 40, 3, 901602, tzinfo=datetime.timezone.utc)),
        ),
    ]
