# Generated by Django 4.2.16 on 2024-11-27 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0008_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 27, 3, 7, 52, 228617, tzinfo=datetime.timezone.utc)),
        ),
    ]
