# Generated by Django 4.2.16 on 2024-11-16 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0012_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 0, 37, 11, 199124, tzinfo=datetime.timezone.utc)),
        ),
    ]
