# Generated by Django 4.2.16 on 2024-11-17 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0023_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 4, 56, 23, 540909, tzinfo=datetime.timezone.utc)),
        ),
    ]
