# Generated by Django 4.2.16 on 2024-11-17 05:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0025_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 6, 45, 33, 148412, tzinfo=datetime.timezone.utc)),
        ),
    ]
