# Generated by Django 4.2.16 on 2024-11-17 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0026_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 17, 6, 48, 7, 7322, tzinfo=datetime.timezone.utc)),
        ),
    ]
