# Generated by Django 4.2.16 on 2024-11-18 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0038_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 8, 39, 26, 28362, tzinfo=datetime.timezone.utc)),
        ),
    ]
