# Generated by Django 4.2.16 on 2024-11-18 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0039_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 21, 30, 25, 393210, tzinfo=datetime.timezone.utc)),
        ),
    ]
