# Generated by Django 4.2.16 on 2024-11-19 23:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0041_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 0, 17, 44, 922664, tzinfo=datetime.timezone.utc)),
        ),
    ]
