# Generated by Django 4.2.16 on 2024-12-05 04:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_events_remove_profile_notifications'),
        ('cal', '0061_alter_event_end_time_alter_event_user_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendee',
            field=models.ManyToManyField(blank=True, related_name='events', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 5, 5, 30, 15, 322498, tzinfo=datetime.timezone.utc)),
        ),
    ]
