# Generated by Django 4.2.17 on 2024-12-06 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0068_alter_event_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 21, 12, 39, 742475, tzinfo=datetime.timezone.utc)),
        ),
    ]
