services:
  app:
    build:
      context: .
      args:
        - DEV=true
    container_name: calendar-app
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py init_superuser &&
             python manage.py runserver 0.0.0.0:8000"
    #env_file:
    #  - ./sample.env.dev
    environment:
      - DJANGO_ENV=dev
      - DB_HOST=onSchedule-db
      - DB_NAME=devdatabase
      - DB_USER=devuser
      - DB_PASS=devpass
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=*
      - S3_STORAGE_BACKEND=0
      - CREATE_SUPERUSER=1
      - DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL:-admin@example.com}
      - DJANGO_SUPERUSER_PASS=${DJANGO_SUPERUSER_PASS:-changeme}
      - DJANGO_SUPERUSER_USER=${DJANGO_SUPERUSER_USER:-admin}
      - PATH=/py/bin:/usr/local/bin:/usr/bin:/bin
    depends_on:
    - postgres

  postgres:
    image: postgres:13-alpine
    container_name: onSchedule-db
    volumes:
      - postgres-calendar:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdatabase
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=devpass


  coverage:
    image: nginx
    ports:
      - '8001:80'
    volumes:
      - ./app/htmlcov:/usr/share/nginx/html
    
volumes:
  postgres-calendar: