# Generated by Django 4.2.16 on 2024-12-04 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cal', '0058_alter_event_end_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestPending', models.BooleanField(default=True)),
                ('viewable', models.BooleanField(default=True)),
                ('Amigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isViewer', models.BooleanField(default=False)),
                ('events', models.ManyToManyField(blank=True, related_name='users', to='cal.event')),
                ('friendList', models.ManyToManyField(blank=True, related_name='users', to='users.friends')),
                ('notifications', models.ManyToManyField(blank=True, related_name='users', to='cal.notifications')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
