# Generated by Django 4.2.16 on 2024-12-03 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0017_alter_event_end_time'),
        ('users', '0003_remove_friends_sharescalendar_friends_requestpending_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, related_name='users', to='cal.notifications'),
        ),
    ]
