# Generated by Django 4.2.7 on 2024-10-30 01:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 2, 42, 46, 618303, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 1, 42, 46, 618303, tzinfo=datetime.timezone.utc)),
        ),
    ]
